export const availablePermissions = {
    merchants: ["view", "actions"],
    admins: ["view", "onboard", "edit", "delete", "block"],
    reports: ["view", "download"],
    wallets: ["view", "viewDetails", "add"],
    merchantCollections: ["view"],
    hub: [
      "view",
      "addApplication",
      "generateApiKey",
      "viewTransactions",
      "editApplication",
      "viewApiKey",
    ],
    queues: ["view"],
    creditDebit: ["view", "processCredit", "processDebit"],
    transactionFilters: ["view"],
    operatorConfig: ["view", "add", "edit"],
    velocityRules: ["view", "add", "edit", "disable"],
    paymentTerminals: ["view", "add", "viewDetails", "disable", "suspend"],
    chargeConfig: ["view", "add", "edit"],
    merchantTier: ["view", "add", "edit"],
    statistics: ["viewDaily", "viewMonthly", "viewWeekly", "viewCumulative"],
    systemLogs: ["view", "viewSummary"],
    payoutReconciliation: ["view", "run", "viewIssues"],
    operatorSwitch: ["view", "manualSwitch", "runAnalysis", "startService"],
    merchantStatistics: ["view", "viewBalanceHistory", "viewBalanceSummary"],
    paymentLinks: ["view"],
    accountBlacklist: ["view", "add", "edit", "disable"],
    systemSettings: ["view", "edit"],
  };